/* tslint:disable */
 

/* auto-generated by NAPI-RS */

export interface FindIconOptions {
    themes?: Array<string>;
    size?: number;
    scale?: number;
}
export declare function findIconPath(
    iconNames: Array<string>,
    options?: FindIconOptions | undefined | null,
): string | null;
